# Esse playbook altera uma linha dentro de um arquivo de texto
---
- name: Altera a linha
  hosts: all
   
  tasks:
    - win_lineinfile:
        path: C:\Users\Administrador\Desktop\texto.txt
        regexp: '(^quarta)'
        line: 'segunda linha'
        #status: absent
