---
# este playbook permite utilizar scripst power shell
- name: Run powershell script
  hosts: all 
  gather_facts: true

  tasks:
    - name: Run powershell script
      var: files/{{shell_executar}}
