---
# este playbook permite utilizar scripst power shell
- name: Run powershell script
  hosts: all 
  gather_facts: false

  tasks:
    - name: Run powershell script
      script: files/{{shell_executar}}
